### ISSUE TITLE
Add possibility to change color of block category titles

### ISSUE THREAD

**Issue by RuneCorp** [LLK/scratch-blocks#2047]
### Expected Behavior
As a developer I would like to be able to change the color of the block category titles (such as "motors", "movements", "light" ++) to match the colors of the blocks. Currently they can only be gray as seen here: 

<img width="250" alt="image" src="https://user-images.githubusercontent.com/779174/76072793-e16e6e80-5f98-11ea-974c-b585633bcd48.png">

**Comment by mrjacobbloom** [comment]
Although it's less convenient than a JS setting, you can use CSS to color these labels. Something like this might do the trick:

```css
.scratchCategoryId-motors > .scratchCategoryMenuItemLabel { color: rgb(51, 115, 204); }
```
