### ISSUE TITLE
consider making blocklyDropDownArrow inherit background-color and border-color

### ISSUE THREAD

**Issue by mrjacobbloom** [LLK/scratch-blocks#500]
``` css
.blocklyDropDownArrow {
  background-color: inherit;
  border-color: inherit;
}
```

Adding this to the CSS (and removing the code that adds inline styles to the arrow) would simplify the process of user-styling dropdown menus with CSS. I've tested it and the functionality appears to be identical.
